### ISSUE TITLE
Prepublishing Nudges : Publish button for stories cut off on Android 10

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#12491]
### Expected behavior
The publish button should be able to the keyboard and navigation bar.
Keyboard closed | keyboard open 
--------|-------
<kbd><img src="https://user-images.githubusercontent.com/1509205/88078731-6ae69d80-cb42-11ea-9296-116fe0d07bd9.png" width="320"></kbd>   |      <kbd><img src="https://user-images.githubusercontent.com/1509205/88078721-67ebad00-cb42-11ea-95e8-fea312484bea.png" width="320"></kbd>
 
### Actual behavior
The button is cut off by the status bar and keyboard. 

### Steps to reproduce the behavior
1. Create a story post. 
2. Press Publish. 
3. See the behavior.

Keyboard closed | Keyboard open 
--------|-------
  <kbd><img src="https://user-images.githubusercontent.com/1509205/88078518-2eb33d00-cb42-11ea-91dd-ced02c340bf7.png" width="320"></kbd>   |       <kbd><img src="https://user-images.githubusercontent.com/1509205/88078532-3246c400-cb42-11ea-9973-c545be63e85d.png" width="320"></kbd>

Tested on Google Pixel 4 XL, Android 10, WPAndroid `wp_alpha2` ()

**Comment by ericamQA** [comment]
Another instance of this reported in zd-3607193

**Comment by jd-alexander** [comment]
Thanks for reporting @wpericam I will look into this.

**Comment by reginabally** [comment]
Another report in 3638952-zen with a video recording attached in the ticket.

Device: Xiaomi Redmi Note 9 Pro ( India ) 
OS: Android 10 
App version: WPAndroid 16.3

**Comment by jd-alexander** [comment]
Thanks for reporting @reginabally we are looking into this issue.

**Comment by jd-alexander** [comment]
I am thinking that the issue might be occurring because a 1-second delay or so might be needed to catch the keyboard opening on this specific device. The problem is I don’t have any immediate way to verify this. I am seeing where some peeps in the mobile division have Xiaomi devices, so I will try my best to reproduce it on the devices I own and if that's not possible, I will seek another way to address this. 

cc @mzorz

**Comment by mzorz** [comment]
> I am thinking that the issue might be occurring because a 1-second delay or so might be needed to catch the keyboard opening on this specific device.

Is there a way we can identify the device model and use something like a map of models -> delay amount in ms? I'm not a fan of having specific behavior but this seems a good enough reason to have something like that (also a map would look a bit more elegant than a hardcoded value anyway). What do you think about that?

> The problem is I don’t have any immediate way to verify this. I am seeing where some peeps in the mobile division have Xiaomi devices

For the record I tested on a Redmi Note 5 here and I couldn't reproduce

**Comment by jd-alexander** [comment]
> Is there a way we can identify the device model and use something like a map of models -> delay amount in ms? I'm not a fan of having specific behavior but this seems a good enough reason to have something like that (also a map would look a bit more elegant than a hardcoded value anyway). What do you think about that?

This is a good idea. In this way, we would only test the delay on `Xiaomi` devices only without introducing a delay for others. Also, this is a good solution because we are able to roll this out in a release, and then we can let the Happiness Engineers check with the Xiaomi users to see if the issue has been resolved. I am going to do this in a PR and I will add you as a reviewer. 

> For the record I tested on a Redmi Note 5 here and I couldn't reproduce

Thanks again for checking this. I appreciate it.

**Comment by jd-alexander** [comment]
I created a [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/13948) to fix this issue as I observed it on Android 11. I am going to keep investigating how/why it would occur on Android 10 as well if it has something to do with how the window inset API operates on different devices/manufacturers.

**Comment by mzorz** [comment]
Didn't intend to close this issue, although I did intend to merge this PR https://github.com/wordpress-mobile/WordPress-Android/pull/13948.  @jd-alexander let me know if this issue should indeed be closed 🙏 thanks!

**Comment by jd-alexander** [comment]
> Didn't intend to close this issue, although I did intend to merge this PR #13948. @jd-alexander let me know if this issue should indeed be closed 🙏 thanks!

Thanks @mzorz I am thinking we could probably leave it open as I am not totally sure if this issue fixes it on Android 10 I know that there have been times when Android versions have had minor versions, eg. `O_MR1` but my investigation so far has not pointed me to this occurrence with version Q. Since this error was also taking place on Xiaomi devices, it could be the case, but the only way to find out is to wait until this fix has been released in production, and the appropriate monitoring is done from a support standpoint to determine this. This fix will be in the 16.7 release so @wpericam & @reginabally could probably check with the users if they updated to that version when it's deployed to the Play Store and if that resolved the issue. If not I will work on finding another solution 🔍

**Comment by reginabally** [comment]
Thank you so much for the update @jd-alexander! I've reached out to the users in 3607193-zen and 3638952-zen and updated them on the status. We'll report back if the users are still having trouble after updating the app to version 16.7.

**Comment by aforcier** [comment]
I'm not sure if it's the same issue but confirming I continue to see this on a Pixel 5, it also happens for the regular post bottom sheet, but not consistently:

![device-2021-04-10-084838](https://user-images.githubusercontent.com/9613966/114250791-d840a400-99d9-11eb-9c15-ae87be18d7a0.png)

If I dismiss and re-show the bottom sheet a few times, the button is sometimes covered, sometimes not.

In the stories screen it does seem to happen every time:

![device-2021-04-10-085014](https://user-images.githubusercontent.com/9613966/114250847-ff977100-99d9-11eb-9377-af452396f2ee.png)

I don't see this on other devices, so I wonder if what I'm seeing is a Pixel 5 issue and not an Android 10 issue.

(Tested on `alpha-286`.)

**Comment by antonis** [comment]
> I don't see this on other devices, so I wonder if what I'm seeing is a Pixel 5 issue and not an Android 10 issue.

I confirm that this is still reproduced on Pixel 5 (WPAndroid `17.3`). My guess is that this is more of an aspect ration issue:
* Pixel 2 XL (18:9): OK
* Pixel 3a (18.5:9): OK
* Pixel 5 (19.5:9): Cut off

**Comment by jd-alexander** [comment]
Thanks for reproducing this @antonis the solution being worked on [here](https://github.com/wordpress-mobile/WordPress-Android/pull/14533) incorporates the aspect ratio from a screen resolution standpoint. You can have a look and if you have any thoughts they are definitely welcome :)
