### ISSUE TITLE
Cannot insert/edit blocks since upgrade to 25.0

### ISSUE THREAD

**Issue by Arrappathor** [wordpress-mobile/WordPress-Android#21005]
### Expected behavior
Editing + inserting blocks is possible.

### Actual behavior
Nothing happens after choosing a block-type, nothing is saved. 
Uploads and classic editor work.

### Steps to reproduce the behavior
Upgrade Wordpress Mobile/Android to Version 25.0 (and also for testing 25.1 rc2) and edit/write a blog-post.

##### Tested on Moto G7 Power, LineageOS21/Android14 / WordpressAndroid 25.0 and Samsung SM-T500 Android13 / WordpressApp 25.1rc2

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by geriux** [comment]
Hey there @Arrappathor 👋 Thank you for reporting this issue and providing additional information. Could you please share a video attempting to reproduce the bug? That would help us identify the problem better.

Thanks!

**Comment by Arrappathor** [comment]
Nothing happens on the screen: new blocks are not inserted and cannot be edited. I can only fill out the title. An empty draft cannot be saved.

**Comment by geriux** [comment]
Hey there @Arrappathor 👋 we are already working on a fix to address this issue, we will let you know once it is shipped.

**Comment by geriux** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/21016 this will ship in `25.1`

**Comment by Arrappathor** [comment]
I'm very sorry, but [25.1RC4](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/25.1-rc-4) and [#21016](https://github.com/wordpress-mobile/WordPress-Android/pull/21016) don't solve the/my problem.
Maybe I have to add: i'm selfhosting my site without jetpack, but with gutenberg.
Thanks for your efforts!

**Comment by geriux** [comment]
@Arrappathor We are sorry you are still having issues, could you please try uninstalling the app and installing RC4 again? I know it's not ideal but it would help us understand the issue better, before uninstalling please make sure you don't have any local drafts that have not been saved so you don't lose any data. Thanks!

**Comment by Arrappathor** [comment]
Uninstalling and re-installing RC4 didn't make it: still can't insert and edit blocks. 
Sorry... 
Thanks for caring!

**Comment by geriux** [comment]
Thanks for trying that, to double-check you're on the right version, if you have time you could please open the app and tap on the "Me" section and then "About WordPress" and confirm you have the following version:

<kbd><img src="https://github.com/wordpress-mobile/WordPress-Android/assets/4885740/4b1a5464-b195-4b86-9aaf-e6a35dd03c0b" width=250 /></kbd>

**Comment by Arrappathor** [comment]
Here you are:

![SmartSelect_20240625-113727_WordPress_113756](https://github.com/wordpress-mobile/WordPress-Android/assets/17974573/d9dee2db-8a51-4e50-a37e-f96e09abe0f0)

**Comment by geriux** [comment]
Hey @Arrappathor 👋 

We are still investigating different scenarios that could affect this issue. Would you mind trying something else if you have some time?

Could you create a new post without an internet connection, e.g., by turning on Airplane mode and then opening the editor, and see if you are able to add content?

Additionally, could you tell us which version of WordPress you are using?

Thanks!

**Comment by Arrappathor** [comment]
WP 6.5.5 (upgraded yesterday)

And you guessed right: it works offline, the draft also has been uploaded later.

![SmartSelect_20240626-122811_WordPress_122822](https://github.com/wordpress-mobile/WordPress-Android/assets/17974573/c8264e29-bcd1-4ba4-9c6f-4d4069e01fd2)

**Comment by geriux** [comment]
Thank you for the information! We appreciate your patience and help as we work on it.

**Comment by geriux** [comment]
Hey there @Arrappathor 👋 we have released a new beta version of the app [25.2-rc-2](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/25.2-rc-2) that should hopefully address this issue.

**Comment by Arrappathor** [comment]
It does! Thank you very much!

**Comment by geriux** [comment]
That's great! Thank you for collaborating with us on getting this resolved, this version will be out in the Play Store in the upcoming weeks. 🚀
